server:
  port: 8081

client:
  id: ccloud-springboot-client-d4b6e617-a023-4542-8043-6b3517a13e73
  address:
      url: http://localhost:8082/addresses

spring:
  data:
    mongodb:
      uri: mongodb+srv://${db_user}:${db_password}@cluster0.sqqj0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: arquitetura_hexagonal
  kafka:
    bootstrap-servers: pkc-56d1g.eastus.azure.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_user} password=${kafka_password};
      session:
        timeout:
          ms: 45000
    producer:
      client-id: spring-boot-producer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG